
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'RSSReader' do
    pod "SwiftDate", "~> 2.0"
    pod 'SWXMLHash', '~> 2.0'
    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireImage', '~> 2.0'
end

